cuisino/Blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.list_of_post, name='list_of_post'),
	url(r'^(?P<slug>[-\w]+)/$', views.post_detail, name='post_detail'),
	url(r'^(?P<slug>[-\w]+)/comment/$', views.add_comment, name='add_comment'),
]

cuisino/cuisino/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include

from home import views as home_views
from Blog import views as Blog_views
from users.views import dashboard, dashboard_auth, dashboard_delete

urlpatterns = [
    path('', home_views.index, name='home'),
    path('admin/', admin.site.urls),
    path('menu/', include('restaurant.urls')),
    path('users/',include('users.urls')),

    path('dashboard/', dashboard, name="dashboard"),
    path('dashboard/auth/<int:id>', dashboard_auth, name="dashboard-auth"),
    path('dashboard/delete/<int:id>', dashboard_delete, name="dashboard-delete"),

    url(r'^blog/', include(('Blog.urls', 'blog'), namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cuisino/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include

from home import views as home_views
from Blog import views as Blog_views

urlpatterns = [
    path('', home_views.index, name='home'),
    path('admin/', admin.site.urls),
    path('menu/', include('restaurant.urls')),
    path('users/',include('users.urls')),

    url(r'^blog/', include(('Blog.urls', 'blog'), namespace='blog')),
    #path('blog/', Blog_views.list_of_post),
    #path('blog/<slug:slug>/', Blog_views.post_detail, name="post_detail"),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cuisino/Blog/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings

from django.urls import reverse

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft','Draft'),
        ('published','Published'),
    )
    #category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE ,related_name='blog_posts')
    complain_compliment_user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE ,related_name='blog_complain')
    published = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=9, choices=STATUS_CHOICES, default=0)

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.slug])

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE ,related_name='comments')
    user = models.CharField(max_length=250)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    complain = models.BooleanField(default=False)
    Reviews = models.DecimalField(range(1,5), max_digits=2, decimal_places=1)

    def approved(self):
        self.approved = True
        self.save()

    def __str__(self):
        return self.user

cuisino/blog/models.py
from django.db import models
from datetime import datetime
from django.urls import reverse
from django.utils.translation import gettext as _
from autoslug.fields import AutoSlugField  #django-autoslug package 
from ckeditor.fields import RichTextField

# Create your models here.
class Blog(models.Model):
    class Meta: 
        verbose_name = 'blog post'
        verbose_name_plural = 'blog posts'
        ordering = ['pub_date']             #date post was published

    title = models.CharField(_('title'), max_length=255)
    slug = AutoSlugField(_('slug'), populate_from='title', unique=True)
    image = models.ImageField(_('image'), blank=True, null=True, upload_to='blog')
    text = RichTextField(_('text'))
    description = models.TextField(_('description'), blank=True, null=True)
    published = models.BooleanField(_('published'), default=False)

    created = models.DateTimeField(_('created'), auto_now_add=True)
    modified = models.DateTimeField(_('modified'), auto_now=True)
    pub_date = models.DateTimeField(_('publish date'), blank=True, null=True)

cuisino/Blog/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('user', 'email', 'body', 'complain', 'Reviews')

cuisino/Blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post

from .forms import CommentForm

def list_of_post(request):
	post = Post.objects.filter(status='published')
	template = 'Blog/post/list_of_post.html'
	context = {'post': post}
	return render(request, template, context)

def post_detail(request, slug):
	post = get_object_or_404(Post, slug=slug)
	template = 'Blog/post/post_detail.html'
	context = {'post': post}
	return render(request, template, context)

def add_comment(request, slug):
	post = get_object_or_404(Post, slug=slug)
	if request.method == 'POST':
		form = CommentForm(request.POST)
		if form.is_valid():
			comment = form.save(commit=False)
			comment.post = post
			comment.save()
			return redirect('blog:post_detail', slug=post.slug)
	else:
		form = CommentForm()
	template = 'Blog/post/add_comment.html'
	context = {'form': form}
	return render(request, template, context)

cuisino/blog/views.py
from django.shortcuts import render

# Create your views here.

cuisino/templates/Blog/post/add_comment.html
{% extends 'Blog/blogBase.html' %}

{% block content %}
	<h1>Add New Comment</h1>
	<form method='POST'>{% csrf_token %}
	{{ form.as_p }}
	<button type = 'submit'>Submit</button>

{% endblock %}

cuisino/templates/Blog/post/list_of_post.html
{% extends 'Blog/blogBase.html' %}

{% block title %}List of blog post{% endblock %}

{% block content %}
	{% for posts in post %}

		<h2><a href="{{posts.get_absolute_url}}">{{ posts.title }}</a> </h2>
		{% if posts.complain == False %}
		<p>Compliment {{ posts.complain_compliment_user }} </p>
		{% else %}
		<p>Complain {{ posts.complain_compliment_user }} </p>
		{% endif %}

		<p>Written by {{ posts.user }} on {{ posts.published }}</p>
		<p>{{ posts.Reviews }}</p>
		<hr>
		{{posts.content|truncatewords:40|linebreaks}}
		
	{% endfor %}
{% endblock %}

cuisino/templates/Blog/post/post_detail.html
{% extends 'Blog/blogBase.html' %}

{% block title %}{{post.user}}{% endblock %}

{% block content %}

		<h2>{{ post.title }} </h2>
		{% if post.complain == False %}
		<p>Like It</p>
		{% else %}
		<p>Don't Like It</p>
		{% endif %}

		<p>Written by {{ post.user }} on {{ post.published }}</p>
		<p>{{ posts.Reviews }}</p>
		<hr>
		{{post.content|linebreaks}}
		<hr>
		<h1>Leave A Comment</h1>
		<p>Total Number Of Comments {{ post.comments.count }}</p>

		<a href="{% url 'blog:add_comment' slug=post.slug %}">Leave A Comment</a>

		{% for comment in post.comments.all %}
			<p>-----------comment-----------</p>
			<p>user {{ comment.user }} created {{ comment.created }}</p>
			<p>{{ comment.body }}</p>
			<p>Stars {{ comment.Reviews }}</p>
		{% empty %}
			<p>There is no comments</p>
		{% endfor %}
			<p>-----------------------------</p>

{% endblock %}