cuisino/cuisino/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include

from home import views as home_views
from Blog import views as Blog_views
from users.views import dashboard, dashboard_auth, dashboard_delete

urlpatterns = [
    path('', home_views.index, name='home'),
    path('admin/', admin.site.urls),
    path('menu/', include('restaurant.urls')),
    path('users/',include('users.urls')),

    path('dashboard/', dashboard, name="dashboard"),
    path('dashboard/auth/<int:id>', dashboard_auth, name="dashboard-auth"),
    path('dashboard/delete/<int:id>', dashboard_delete, name="dashboard-delete"),

    url(r'^blog/', include(('Blog.urls', 'blog'), namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cuisino/restaurant/urls.py
from django.urls import path, re_path
from django.conf.urls import url
import restaurant.views as views

app_name = 'restaurant'


urlpatterns=[
    path('', views.index, name="menu"),
    path('register/', views.register, name="register"),
    path('<int:id>/', views.cartitem, name="menuitem"),
    path('<int:id>/delete/', views.delete, name="delete"),
    path('complete-order/<uuid:id>', views.complete_order, name="complete-order"),
    path('complete-order/<uuid:id>/reservation/', views.complete_order_reservation, name="complete-order-reservation"),
    path('complete-order/<uuid:id>/delivery/', views.complete_order_delivery, name="complete-order-delivery"),
    path('complete-order/<uuid:id>/pickup/', views.complete_order_pickup, name="complete-order-pickup"),
    path('invoice/<str:status>', views.invoice, name="invoice"),

    path('cart/', views.cart, name="cart"),
    path('cart/add/<int:itemID>/<int:quantity>', views.add_to_cart, name="add-to-cart"),
    path('cart/remove/<int:itemID>', views.remove_from_cart, name="remove-from-cart"),

    path('search/', views.SearchResultsView, name='search_results'),
]

cuisino/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include

from home import views as home_views
from Blog import views as Blog_views

urlpatterns = [
    path('', home_views.index, name='home'),
    path('admin/', admin.site.urls),
    path('menu/', include('restaurant.urls')),
    path('users/',include('users.urls')),

    url(r'^blog/', include(('Blog.urls', 'blog'), namespace='blog')),
    #path('blog/', Blog_views.list_of_post),
    #path('blog/<slug:slug>/', Blog_views.post_detail, name="post_detail"),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cuisino/users/urls.py
from django.conf.urls import url
from django.urls import path

from users import views

app_name = 'users'


urlpatterns=[
    path('', views.index, name="index"),

    path('register/', views.register, name='register'),
    path('apply/', views.apply, name='apply'),

    path('user_login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),

    path('AddDeposit/', views.AddDeposit, name='AddDeposit'),
]

cuisino/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone

class Users(AbstractUser):
    CUSTOMER = 1
    CHEF = 2
    DELIVERY_BOY = 3
    ADMIN = 4 # This is going to be the owner

    ROLE_CHOICES = [
        ( CUSTOMER, 'Customer' ),
        ( CHEF, 'Chef' ),
        ( DELIVERY_BOY, 'Delivery Boy' ),
        ( ADMIN, 'Admin' )
    ]

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

    id = models.AutoField(primary_key=True)
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, default=CUSTOMER)
    messages = models.TextField(null=True, blank=True)
    demoted = models.BooleanField(default=False)
    is_auth_by_manager = models.BooleanField(default=False)

    # customer
    warnings = models.IntegerField(blank=True, null=True)
    VIP = models.BooleanField(blank=True, null=True)
    deposit = models.DecimalField(decimal_places=2, max_digits=5, blank=True, null=True)
    # employee
    salary = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)

    USERNAME_FIELD = 'username'

cuisino/users/views.py
from django.shortcuts import render, redirect
from users.forms import UserForm, EmployeeApplyForm
from better_profanity import profanity
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from users.models import Users


"""
    This function links to homepage
"""
def index(request):
    return render(request,'users/index.html')

"""
    This function adds a user as an employee. Can either be a chef or a delivery guy.
"""
def apply(request):
    return render(request, 'users/register.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

def register(request):

    registered = False

    if request.method == 'POST':

        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.set_password(user.password)
            user.save()
            registered = True

        else:
            print(form.errors)

    else:
        form = UserForm()

    return render(request,'users/register.html',
                           { 'form': form, 'registered': registered })

def apply(request):
    registered = False

    if request.method == 'POST':
        form = EmployeeApplyForm(data=request.POST)
        if form.is_valid():
            employee = form.save()
            employee.set_password(employee.password)
            employee = form.save()
            registered = True
        else:
            print(user_form.errors)

    elif request.method == 'GET':
        form = EmployeeApplyForm()

    return render(request, 'users/apply.html', { 'form': form, 'registered': registered })

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                if user.is_auth_by_manager or user.role == user.ADMIN:
                    login(request,user)
                    return redirect('../')
                else:
                    return render(request, 'users/index.html', {})
            else:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        return render(request, 'users/login.html', {})

@login_required
def dashboard(request):
    unathenticated_users = Users.objects.filter(is_auth_by_manager=False)
    print(unathenticated_users)
    return render(request, 'admin/dashboard.html', { 'users': unathenticated_users })

@login_required
def dashboard_auth(request, id):
    user = Users.objects.get(id=id)
    user.is_auth_by_manager = True
    user.save()
    return redirect("/dashboard/")

@login_required
def dashboard_delete(request, id):
    Users.objects.filter(id=id).delete()
    return redirect("/dashboard/")

def taboo_censor(request):
    if __name__ == "__main__":
        profanity.load_censor_words()

        # text = #Once Blog Implemented, string of text that gets submitted will be scanned here
        text = ''

        text = profanity.censor(text)




def taboo_checker(request):
    count = 0
    item = Users.objects.get(warnings)
    if __name__ == "__main__":
        # text = #Once Blog Implemented, string of text that gets submitted will be scanned here
        text = ''

        if profanity.contains_profanity(text) == True:
            item.warnings += 1
            VIP_to_Reg()
            Reg_to_Rip()

def VIP_to_Reg():
    item = Users.objects.get(warnings,VIP)
    if item.VIP == True and item.warnings == 2:
        item.VIP = False
        item.warnings = 0


def Reg_to_Rip(id):
    item = Users.objects.get(VIP,id,warnings)
    if item.VIP == False and item.warnings == 3:
        Users.objects.filter(id=id).delete()
        return redirect ('logout/')


def AddDeposit(request):
    if 'd' in request.GET and request.GET['d']:
        d = request.GET['d']
        depo = request.user.deposit
        d = float(depo) + float(d)
        userdepo = Users.objects.update(deposit=d)


        return redirect( '../')

cuisino/templates/users/apply.html
{% extends 'base/formbase.html' %}
{% load static %}
{% load bootstrap3 %}


<title>Assiette de Poséidon ψ Career Registeration Page</title>

{% block setting %}
<div class="col-xl-9" style="padding-left: auto; padding-right: 0%; ">

    <div class="card2 card border-0 px-4 py-4">
        {% if registered %}
          <h1>You have been Registered!</h1>
        {% else %}
        <div class="row mb-4 px-3">
            <h2 class="mb-0 mr-4 mt-1">Career Registration</h2>
        </div>
        <div class="row mb-4 px-3">
            <h4 class="mb-0 mr-4 mt-2">Sail with us</h4>
        </div>
        <div class="row px-3 mb-4">
            <div class="line"></div>
            <div class="line"></div>
        </div>
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="row mb-3 px-3"> <button type="submit" class="btn btn-blue text-center">Register</button> </div>
        </form>
        {% endif %}
    </div>
</div>

{% endblock setting %}

cuisino/templates/users/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'css/project/main.css' %}"/>
        {% block stylesheets %}
        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-primary">
            <div class="container">
                <ul class="navbar-nav">
                    <li class="nav-item"> <a class="navbar-brand" href="{%url 'home'%}">HOME</a></li>

                    <li class="nav-item"> <a class="nav-link" href="{%url 'restaurant:menu'%}">Menu</a></li>


                </ul>
                <ul class="navbar-nav justify-content-end">
                    {% if user.is_authenticated %}
                        <li class="nav-item"> <a class="nav-link" href="{%url 'users:index'%}">Account</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'users:user_logout' %}">Logout</a></li>
                        {% if user.role == user.CHEF or user.role == user.ADMIN %}
                            <li class="nav-item"> <a class="nav-link" href="{%url 'restaurant:register'%}">Menu Form</a></li>
                        {% endif %}
                        {% if  user.role == user.ADMIN %}
                            <li class="nav-item"> <a class="nav-link" href="{%url 'admin:index'%}">Admin</a></li>
                        {% elif user.role == user.CUSTOMER %}
                            <li class="nav-item"><a class="nav-link text-dark" href="{% url 'restaurant:cart' %}"><i class="fa fa-shopping-bag"></i></a></li>
                        {% endif %}
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'users:user_login' %}">Login</a></li>
                        <li class="nav-item"> <a class="nav-link" href="{%url 'users:register'%}">Register</a></li>
                        <li class="nav-item"> <a class="nav-link" href="{%url 'users:apply'%}">Careers</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>


        <!-- <div class="user_surfer">
        <center><h1>Welcome surfer!</h1></center>
        </div>

        <div class="user_member">
        <center><h1>Welcome member!</h1></center>
        </div>

        <div class="chef">
        <center><h1>Welcome chef!</h1></center>
        </div>

        <div class="manager">
        <center><h1>Welcome Manager!</h1></center>
        </div> -->


        {% block body_block %}
        {% endblock %}


        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

cuisino/templates/users/index.html
{% extends 'base/formbase.html' %}
{% load static %}



<title>Assiette de Poséidon ψ Member Account Page</title>
{% block setting %}
<div class="col-xl-9" style="padding-left: auto; padding-right: 0%; ">
    <div class="card2 card border-0 px-4 py-4">
        <div class="row mb-4 px-3">
            <h2 class="mb-0 mr-4 mt-1">Account Information</h2>
        </div>
        <div class="row mb-4 px-3">
            {% if user.is_authenticated %}
                <h4>Welcome {{ user.username }}!</h4>
                <p> <br> </p>

            {% else %}
                <h2>Welcome to the site!</h2>
                <h2>Your account is not active yet.</h2>
                <h2>Please wait for a manager to authenticate your account.</h2>
            {% endif %}
        </div>
        <div class="row px-3 mb-4">
            <div class="line"></div>
            <div class="line"></div>
        </div>
        {# for customer's perspective  #}
        {% if user.is_authenticated and user.role == user.CUSTOMER %}

        <div class="row px-3">
            <label class="mb-1">
                <h6>Balance: {{ user.deposit }}</h6>
                <br>
                <h6>Warnings: {{ user.warnings }}</h6>
                <br>
                <h6>Membership status:
                {% if user.VIP == True %}
                    VIP
                {% else %}
                    Registered
                {% endif %}
                Membership
                </h6>
                <form class="d-flex" action="{% url 'users:AddDeposit' %}" method="get">
                  <input name="d" type="text" placeholder="Add deposit amount" id="myInput" onkeyup="filterFunction()">
                  <button class="btn btn-primary" type="submit">Deposit</button>
                </form>
            </label>
        </div>
        {# gotta add for order in order_list here #}

        {% elif user.is_authenticated %}

        <div class="row px-3">
            <label class="mb-1">
                <h5>How are you?</h5>
                <br>
                <h6>Salary: {{ user.salary }}</h6>

            </label>
        </div>
        {% endif %}

    </div>
</div>
{% endblock setting %}

cuisino/templates/users/login.html
{% extends 'base/formbase.html' %}
{% load static %}




<title>Assiette de Poséidon ψ Login Page</title>


{% block setting %}
            <div class="col-xl-9" style="padding-left: auto; padding-right: 0%; ">
                <div class="card2 card border-0 px-4 py-4">
                    <div class="row mb-4 px-3">
                        <h2 class="mb-0 mr-4 mt-1">Member Login</h2>
                    </div>
                    <div class="row px-3 mb-4">
                        <div class="line"></div>
                        <div class="line"></div>
                    </div>
                    <form method="POST">
                        {% csrf_token %}
                        <div class="row px-3">
                            <label class="mb-1">
                                <h6 class="mb-0 text-sm">Username</h6>
                            </label>
                            <input class="mb-4" type="text" name="username" placeholder="Enter username">
                        </div>
                        <div class="row px-3"> <label class="mb-1">
                                <h6 class="mb-0 text-sm">Password</h6>
                            </label> <input type="password" name="password" placeholder="Enter password"> </div>
                        <div class="row px-3 mb-4">
                            <div class="custom-control custom-checkbox custom-control-inline"> <input id="chk1" type="checkbox" name="chk" class="custom-control-input"> <label for="chk1" class="custom-control-label text-sm">Remember me</label> </div> <a href="#" class="ml-auto mb-0 text-sm">Forgot Password?</a>
                        </div>
                        <div class="row mb-3 px-3"> <button type="submit" class="btn btn-blue text-center">Login</button> </div>
                        <div class="row mb-4 px-3"> <small class="font-weight-bold">Don't have an account? <a class="text-primary ">Register</a></small> </div>
                    </form>
                </div>
            </div>
        </div>
{% endblock %}

cuisino/templates/users/register.html
{% extends 'base/formbase.html' %}
{% load static %}
{% load bootstrap3 %}


<title>Assiette de Poséidon ψ Member Registeration Page</title>

{% block setting %}
<div class="col-xl-9" style="padding-left: auto; padding-right: 0%; ">

    <div class="card2 card border-0 px-4 py-4">
        {% if registered %}
          <h1>You have been Registered!</h1>
        {% else %}
        <div class="row mb-4 px-3">
            <h2 class="mb-0 mr-4 mt-1">Member Registration</h2>
        </div>
        <div class="row mb-4 px-3">
            <h4 class="mb-0 mr-4 mt-2">Dine with us</h4>
        </div>
        <div class="row px-3 mb-4">
            <div class="line"></div>
            <div class="line"></div>
        </div>
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}

            <div class="row mb-3 px-3"> <button type="submit" class="btn btn-blue text-center">Register</button> </div>
        </form>
        {% endif %}
    </div>
</div>

{% endblock setting %}