cuisino/Blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.list_of_post, name='list_of_post'),
	url(r'^(?P<slug>[-\w]+)/$', views.post_detail, name='post_detail'),
	url(r'^(?P<slug>[-\w]+)/comment/$', views.add_comment, name='add_comment'),
]

cuisino/cuisino/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include

from home import views as home_views
from Blog import views as Blog_views
from users.views import dashboard, dashboard_auth, dashboard_delete

urlpatterns = [
    path('', home_views.index, name='home'),
    path('admin/', admin.site.urls),
    path('menu/', include('restaurant.urls')),
    path('users/',include('users.urls')),

    path('dashboard/', dashboard, name="dashboard"),
    path('dashboard/auth/<int:id>', dashboard_auth, name="dashboard-auth"),
    path('dashboard/delete/<int:id>', dashboard_delete, name="dashboard-delete"),

    url(r'^blog/', include(('Blog.urls', 'blog'), namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cuisino/restaurant/urls.py
from django.urls import path, re_path
from django.conf.urls import url
import restaurant.views as views

app_name = 'restaurant'


urlpatterns=[
    path('', views.index, name="menu"),
    path('register/', views.register, name="register"),
    path('<int:id>/', views.cartitem, name="menuitem"),
    path('<int:id>/delete/', views.delete, name="delete"),
    path('complete-order/<uuid:id>', views.complete_order, name="complete-order"),
    path('complete-order/<uuid:id>/reservation/', views.complete_order_reservation, name="complete-order-reservation"),
    path('complete-order/<uuid:id>/delivery/', views.complete_order_delivery, name="complete-order-delivery"),
    path('complete-order/<uuid:id>/pickup/', views.complete_order_pickup, name="complete-order-pickup"),
    path('invoice/<str:status>', views.invoice, name="invoice"),

    path('cart/', views.cart, name="cart"),
    path('cart/add/<int:itemID>/<int:quantity>', views.add_to_cart, name="add-to-cart"),
    path('cart/remove/<int:itemID>', views.remove_from_cart, name="remove-from-cart"),

    path('search/', views.SearchResultsView, name='search_results'),
]

cuisino/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include

from home import views as home_views
from Blog import views as Blog_views

urlpatterns = [
    path('', home_views.index, name='home'),
    path('admin/', admin.site.urls),
    path('menu/', include('restaurant.urls')),
    path('users/',include('users.urls')),

    url(r'^blog/', include(('Blog.urls', 'blog'), namespace='blog')),
    #path('blog/', Blog_views.list_of_post),
    #path('blog/<slug:slug>/', Blog_views.post_detail, name="post_detail"),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cuisino/users/urls.py
from django.conf.urls import url
from django.urls import path

from users import views

app_name = 'users'


urlpatterns=[
    path('', views.index, name="index"),

    path('register/', views.register, name='register'),
    path('apply/', views.apply, name='apply'),

    path('user_login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),

    path('AddDeposit/', views.AddDeposit, name='AddDeposit'),
]

cuisino/templates/base/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'css/project/main.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/users/main.css' %}">
        {% block stylesheets %}
        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container">
                <ul class="navbar-nav">
                    <li class="nav-item"> <a class="navbar-brand active" href="{%url 'home'%}">HOME</a></li>
                    <li class="nav-item"> <a class="nav-link active" href="{%url 'restaurant:menu'%}">Menu</a></li>

                    <li class="nav-item"> <a class="nav-link active" href="{% url 'blog:list_of_post' %}">Blog</a></li>



                </ul>

                <ul class="navbar-nav justify-content-end">
                    {% if user.is_authenticated %}
                        <li class="nav-item"> <a class="nav-link active" href="{%url 'users:index'%}">Account</a></li>
                        <li class="nav-item"><a class="nav-link active" href="{% url 'users:user_logout' %}">Logout</a></li>

                        {% if user.role == user.CHEF or user.role == user.ADMIN %}
                            <li class="nav-item"> <a class="nav-link active" href="{%url 'restaurant:register'%}">Menu Form</a></li>
                        {% endif %}
                        {% if  user.role == user.ADMIN %}
                            <li class="nav-item"> <a class="nav-link active" href="{%url 'admin:index'%}">Admin</a></li>
                            <li class="nav-item"> <a class="nav-link active" href="{%url 'dashboard'%}">Dashboard</a></li>
                        {% elif user.role == user.CUSTOMER %}
                            <li class="nav-item"><a class="nav-link text-dark active" href="{% url 'restaurant:cart' %}"><i class="fa fa-shopping-bag"></i></a></li>
                        {% endif %}
                    {% else %}
                        <li class="nav-item"><a class="nav-link active" href="{% url 'users:user_login' %}">Login</a></li>
                        <li class="nav-item"> <a class="nav-link active" href="{%url 'users:register'%}">Register</a></li>
                        <li class="nav-item"> <a class="nav-link active" href="{%url 'users:apply'%}">Careers</a></li>
                    {% endif %}


                    <form class="d-flex" action="{% url 'restaurant:search_results' %}" method="get">
                      <input name="q" type="text" placeholder="Search.." id="myInput" onkeyup="filterFunction()">
                      <button class="btn btn-primary" type="submit">Search</button>
                    </form>

                </ul>
            </div>
        </nav>


        <!-- <div class="user_surfer">
        <center><h1>Welcome surfer!</h1></center>
        </div>

        <div class="user_member">
        <center><h1>Welcome member!</h1></center>
        </div>

        <div class="chef">
        <center><h1>Welcome chef!</h1></center>
        </div>

        <div class="manager">
        <center><h1>Welcome Manager!</h1></center>
        </div> -->


        {% block body_block %}
        {% endblock %}


        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

cuisino/templates/base/formbase.html
{% extends 'base/base.html' %}
{% load static %}
{% load bootstrap3 %}



{% block body_block %}

<div class="container-fluid px-1 px-md-5 px-lg-1 px-xl-5 py-4 mx-auto" style="width: 80%; margin-left: auto; margin-right: auto;">
    <div class="card card0 border-0"  style="background-color: rgba(255, 255, 255, 0.9); ">
        <div class="row d-flex">
                    <div class="row" style="display: flex; ">
                        <img src="{% static 'img/logo.png' %}" class="logo">
                    </div>
            {% block setting %}{% endblock setting %}
        </div>
        <div class="bg-primary py-4" style="height: 15px">
            <div class="row px-3">
                <small class="ml-4 ml-sm-5 mb-2">Copyright &copy; 2020. All rights reserved.</small>
                <div class="social-contact ml-4 ml-sm-auto"> <span class="fa fa-facebook mr-4 text-sm"></span> <span class="fa fa-google-plus mr-4 text-sm"></span> <span class="fa fa-linkedin mr-4 text-sm"></span> <span class="fa fa-twitter mr-4 mr-sm-5 text-sm"></span> </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}